#!/usr/bin/env python3

import json
import shutil
from pathlib import Path
from subprocess import run

LEAN_PATH = Path("src")
ILEAN_PATH = Path("build/release/stage1/lib/lean")

def main():
    print("x y")

    leans = [p.relative_to(LEAN_PATH) for p in LEAN_PATH.rglob("*.lean")]
    for lean in leans:
        lean_file = LEAN_PATH / lean
        ilean_file = ILEAN_PATH / lean.with_suffix(".ilean")
        if not ilean_file.exists():
            # print(f"No ilean for {lean}")
            continue
        lean_size = lean_file.stat().st_size
        ilean_size = ilean_file.stat().st_size
        # with open(ilean_file) as f:
        #     if json.load(f)["references"]:
        #         continue
        print(f"{lean_size} {ilean_size}")
        # if ilean_size < 1e2:
        #     print()
        #     print()
        #     print(lean)
        #     print(">"*80)
        #     with open(lean_file) as f:
        #         for line in f:
        #             print(f"    {line.rstrip()}")
        #     print("="*80)
        #     with open(ilean_file) as f:
        #         for line in f:
        #             print(f"    {line.rstrip()}")
        #     print("<"*80)

if __name__ == "__main__":
    main()
