#!/usr/bin/env python3

import json
from collections import Counter
from pathlib import Path

ILEAN_PATH = Path("build/release/stage1/lib/lean")

def main():
    count = Counter()
    for p in ILEAN_PATH.rglob("*.ilean"):
        with open(p) as f:
            ilean = json.load(f)
        for name, info in ilean["references"].items():
            if info.get("definition", None):
                count[name] += 1
            count[name] += len(info["usages"])

    for name, amount in count.most_common(20):
        # print(f"{amount:4}: {name[2:]}")
        print(f"\\lstinline!{name[2:]}! & {amount} & \\\\")

if __name__ == "__main__":
    main()
